### ISSUE TITLE
Tasks with unexpectedly late expiration dates.

### ISSUE THREAD

**Issue by kraney** [uber/cadence#4077] opened 2021-03-25 21:53 UTC
**Describe the bug**
Related to #4509 - we have some tasks in our tasks table that have expiration dates far in the future. Their presence disrupts the scavenger leading to accumulating cruft in the database.

Related but perhaps different, these really long expirations are actually interpreted incorrectly and look like they are in the past when logged from the go code - "Expires 1754-08-30 22:43:41.128654848 +0000 UTC" - which I presume is an overflow error when converting from 64-bit epoch nanoseconds as stored in the DB to 32-bit epoch seconds as converted into a struct time.TIme.

Example task info:
* task_list_name: LaunchpadTaskList2
* task_type: 0
* task_id: 900006
* workflow_id: 36d44f74-1526-49f8-bb31-4c66f229a89f
* runID: d866ee08-5b94-46ad-9fbf-681063ad58a4
* scheduleID: 2
* expiryTimeNanos: 11651379494838206464 (Tuesday, March 21, 2339 10:18:14.838 PM)
* createdTimeNanos: 1607407202826576748 (Tuesday, December 8, 2020 6:00:02.826 AM)

from task list:
* kind: 0
* ackLevel: 0
* expiryTimeNanos: 0
* lastUpdatedNanos: 1616693232636248417 (Thursday, March 25, 2021 5:27:12.636 PM)

I believe this workflow is scheduled via Cron. This particular run is old enough there is no data available about it specifically.

Another example:
* task_list_name: ufo-cadence-worker-7f8cfcf758-4nzkw:dfe0d11a-0351-47f8-ae4b-ba5d541998bf
* task_type: 0
* task_id: 3403639
* workflow_id: 5552038a-4153-465e-a6a9-0dcf0f813825~ufo~MultiStationFullOrderFeedCleanupWorkflow
* runID: 94292234-c16a-4390-9bfd-cac6a88cf09e
* scheduleID: 16
* expiryTimeNanos: 11651379494838206464 (Tuesday, March 21, 2339 10:18:14.838 PM)
* createdTimeNanos: 1614111529650574169 (Tuesday, February 23, 2021 8:18:49.650 PM)

from task list
* kind: 1
* ackLevel: 3403502
* expiryTimeNanos: 1616623122469050635 (Wednesday, March 24, 2021 9:58:42.469 PM)
* lastUpdatedNanos: 1616689795554505924 (Thursday, March 25, 2021 4:29:55.554 PM)

This run is recent enough to have info available:
```
   1  WorkflowExecutionStarted    {WorkflowType:{Name:MultiStationFullOrderFeedCleanupWorkflow::start},
                                  TaskList:{Name:UfoTaskList}, Input:[���
                                  $5552038a-4153-465e-a6a9-0dcf0f813825$d33b93b7-9392-40e9-b755-aa8d08162b89
                                                                                                           �����0"$47fd1570-eafd-4a96-
                                  b4f3-d49921a5174d], ExecutionStartToCloseTimeoutSeconds:2678400,
                                  TaskStartToCloseTimeoutSeconds:30, ContinuedFailureDetails:[],
                                  LastCompletionResult:[], OriginalExecutionRunId:94292234-c16a-4390-9bfd-cac6a88cf09e,
                                  FirstExecutionRunId:94292234-c16a-4390-9bfd-cac6a88cf09e, Attempt:0, FirstDecisionTaskBackoffSeconds:0}
   2  DecisionTaskScheduled       {TaskList:{Name:UfoTaskList},
                                  StartToCloseTimeoutSeconds:30,
                                  Attempt:0}
   3  DecisionTaskStarted         {ScheduledEventId:2,
                                  Identity:1@ufo-cadence-worker-7954d9fcdf-cjkj9,
                                  RequestId:808db30d-0f6e-4e99-bac8-53bfec752d36}
   4  DecisionTaskCompleted       {ExecutionContext:[],
                                  ScheduledEventId:2, StartedEventId:3,
                                  Identity:1@ufo-cadence-worker-7954d9fcdf-cjkj9}
   5  MarkerRecorded              {MarkerName:Version, Details:[1], DecisionTaskCompletedEventId:4,
                                  Header:{Fields:map{MutableMarkerHeader:{"id":"addJitter","eventId":5,"accessCount":0}}}}
   6  TimerStarted                {TimerId:1,
                                  StartToFireTimeoutSeconds:2664707,
                                  DecisionTaskCompletedEventId:4}
   7  TimerFired                  {TimerId:1, StartedEventId:6}
   8  DecisionTaskScheduled       {TaskList:{Name:ufo-cadence-worker-7954d9fcdf-cjkj9:33813fda-a6fb-4c5a-b3b2-35058436ac18},
                                  StartToCloseTimeoutSeconds:30, Attempt:0}
   9  DecisionTaskTimedOut        {ScheduledEventId:8,
                                  StartedEventId:0,
                                  TimeoutType:SCHEDULE_TO_START}
  10  DecisionTaskScheduled       {TaskList:{Name:UfoTaskList},
                                  StartToCloseTimeoutSeconds:30,
                                  Attempt:0}
  11  DecisionTaskStarted         {ScheduledEventId:10,
                                  Identity:1@ufo-cadence-worker-7f8cfcf758-4nzkw,
                                  RequestId:4078e18d-705a-46bc-b558-d6d928cbddca}
  12  DecisionTaskCompleted       {ExecutionContext:[],
                                  ScheduledEventId:10, StartedEventId:11,
                                  Identity:1@ufo-cadence-worker-7f8cfcf758-4nzkw}
  13  ActivityTaskScheduled       {ActivityId:2, ActivityType:{Name:MultiStationFullOrderCleanupActivity::removeFeedItems},
                                  TaskList:{Name:UfoTaskList}, Input:[
                                  $5552038a-4153-465e-a6a9-0dcf0f813825$d33b93b7-9392-40e9-b755-aa8d08162b89
                                                                                                           �����0"$47fd1570-eafd-4a96-b4f3-d499
                                  21a5174d], ScheduleToCloseTimeoutSeconds:300, ScheduleToStartTimeoutSeconds:300, StartToCloseTimeoutSeconds:300,
                                  HeartbeatTimeoutSeconds:300, DecisionTaskCompletedEventId:12, RetryPolicy:{InitialIntervalInSeconds:5,
                                  BackoffCoefficient:2, MaximumIntervalInSeconds:30, MaximumAttempts:0, NonRetriableErrorReasons:[len=0],
                                  ExpirationIntervalInSeconds:300}}
  14  ActivityTaskStarted         {ScheduledEventId:13,
                                  Identity:1@ufo-cadence-worker-7f8cfcf758-4nzkw,
                                  RequestId:917e517e-707b-4733-a4af-8321227b6430,
                                  Attempt:0}
  15  ActivityTaskCompleted       {Result:[], ScheduledEventId:13,
                                  StartedEventId:14,
                                  Identity:1@ufo-cadence-worker-7f8cfcf758-4nzkw}
  16  DecisionTaskScheduled       {TaskList:{Name:ufo-cadence-worker-7f8cfcf758-4nzkw:dfe0d11a-0351-47f8-ae4b-ba5d541998bf},
                                  StartToCloseTimeoutSeconds:30, Attempt:0}
  17  DecisionTaskTimedOut        {ScheduledEventId:16,
                                  StartedEventId:0,
                                  TimeoutType:SCHEDULE_TO_START}
  18  DecisionTaskScheduled       {TaskList:{Name:UfoTaskList},
                                  StartToCloseTimeoutSeconds:30,
                                  Attempt:0}
  19  DecisionTaskStarted         {ScheduledEventId:18,
                                  Identity:1@ufo-cadence-worker-7f8cfcf758-4nzkw,
                                  RequestId:916f08dc-1d2f-4578-9f59-acfbdc736248}
  20  DecisionTaskCompleted       {ExecutionContext:[],
                                  ScheduledEventId:18, StartedEventId:19,
                                  Identity:1@ufo-cadence-worker-7f8cfcf758-4nzkw}
  21  WorkflowExecutionCompleted  {Result:[],
                                  DecisionTaskCompletedEventId:20}
```

One thing of note - it looks like the scheduleID in question actually timed out. But the task is still present in the tasks table, now with a weird timeout value.

Based on this, I suspect it's related to code in `service/matching/taskListManager.go` with this comment:
```
		// failed to start the task.
		// We cannot just remove it from persistence because then it will be lost.
		// We handle this by writing the task back to persistence with a higher taskID.
		// This will allow subsequent tasks to make progress, and hopefully by the time this task is picked-up
		// again the underlying reason for failing to start will be resolved.
		// Note that RecordTaskStarted only fails after retrying for a long time, so a single task will not be
		// re-written to persistence frequently.
```
Possibly in response to the partition-related code that forwards a task.

**To Reproduce**
I don't know how it came about, I only see the evidence it has. So I don't know how to reproduce or even if it's still possible.

**Steps to reproduce the behavior:**
Unknown

**Expected behavior**
I'm given to understand that there should be an upper bound on task expiration, so I would expect no task would have an expiration time like this.

**Screenshots**

**Additional context**
Add any other context about the problem here, E.g. Stackstace, workflow history.

**Comment by longquanzheng** [comment] 2021-03-25 22:46
What is the server of Cadence server that can run into this? 

This is very important as we are very likely to go over the code path to see what's wrong.

**Comment by longquanzheng** [comment] 2021-03-26 17:11
@kraney do you know the versions ?

**Comment by kraney** [comment] 2021-03-26 18:10
We're running from a fork that's been patched. It makes this slightly hard to answer. Will try to get back with an answer...

**Comment by kraney** [comment] 2021-03-26 18:13
Forked originally from sha 4c9950600c61ace9a2948623e4bfb26f87e9c9b0, around 0.10.1 time frame I think based on tags. But some fixes have been cherry picked following that.

**Comment by kraney** [comment] 2021-03-26 18:14
Actually maybe that's v0.19.0 based on the info github linked to from the sha

**Comment by longquanzheng** [comment] 2021-03-26 18:21
> Actually maybe that's v0.19.0 based on the info github linked to from the sha

If you forked from a release tag, I think it's 0.12.0: https://github.com/uber/cadence/releases/tag/v0.12.0 (released 1.2 year ago)
the commit goes out in that release.

But looks like it's not from that release because the commit is not the latest commit of the tag.So it's possible around 0.10

0.19.0 is not out yet. The latest release is 0.18.2. Not sure why Github links them together.

I think the easiest way is to push your forked&patched Cadence server code into Github. Do you think it's possible?

Also, do you think it would be easier to try out 0.18.2 to see if it fixes the bug? AFAIK, the matching service wasn't that stable back to a year ago, especially when we were working on scalable tasklist feature.

**Comment by kraney** [comment] 2021-03-26 19:02
It won't be possible to push up the fork. Also I can't just directly switch to 0.18.2, although it may be possible to pick up the fixes up to that release. It won't happen very quickly.

**Comment by longquanzheng** [comment] 2021-03-26 19:13
> Not sure why Github links them together.

I think I figured it out. 
<img width="904" alt="Screen Shot 2021-03-26 at 12 11 59 PM" src="https://user-images.githubusercontent.com/4523955/112681893-8ec65580-8e2c-11eb-9d5c-c1dab6110620.png">
The commit exists in all versions from 0.12 to 0.19 


> It won't be possible to push up the fork. Also I can't just directly switch to 0.18.2, although it may be possible to pick up the fixes up to that release. It won't happen very quickly.

Okay..It's a problem. 
No one knows which commits fix the bug, if we don't know the root cause of it. If you just pick up all changes to 0.18.2, there will be too many and I am not sure that will be doable.

**Comment by kraney** [comment] 2021-03-26 20:36
I understand it's a problem. There are other complications as well - there's no immediate way to trigger this event. So having changed releases, it will be difficult to know if the problem is actually solved - it's only possible to confirm, at some future date, that it _wasn't_ solved if similar tasks show up. I can't even say for certain it hasn't already been patched away in what we're running today. So I know YMMV on this report.

**Comment by meiliang86** [comment] 2021-04-01 23:47
@kraney I'm going to close this for now. It would be better if you can find a way to keep your server version up to date so we can look at issues in a more efficient way.

**Closed by meiliang86** 2021-04-01 23:47 UTC
