### ISSUE TITLE
Worker (activity) panic errors 

### ISSUE THREAD

**Issue by Gogetter** [uber/cadence#3910] opened 2021-01-21 14:18 UTC
**Describe the bug**
We currently have Cadence running but seeing the below error from the cadence-worker service
```json
{"level":"error","ts":1611236070.6994076,"caller":"internal/internal_task_handlers.go:1784","msg":"Activity panic.","Domain":"cadence-system","TaskList":"cadence-sys-tl-scanner-tasklist-0","WorkerID":"1@craig-test-cadence-worker-85888dc89b-4gdfv@cadence-sys-tl-scanner-tasklist-0","WorkflowID":"cadence-sys-tl-scanner","RunID":"6e554837-ca3a-46c2-8ec1-97070b233dcc","ActivityType":"cadence-sys-tl-scanner-scvg-activity","PanicError":"interface conversion: interface {} is nil, not scanner.scannerContext","PanicStack":"activity for cadence-sys-tl-scanner-tasklist-0 [panic]:\ngithub.com/uber/cadence/service/worker/scanner.TaskListScavengerActivity(0x27eda60, 0xc000d2b8c0, 0x0, 0x0)\n\t/cadence/service/worker/scanner/workflow.go:192 +0x6b8\nreflect.Value.call(0x1e97780, 0x2398b80, 0x13, 0x22b4706, 0x4, 0xc0003d3560, 0x1, 0x1, 0x1, 0x0, ...)\n\t/usr/local/go/src/reflect/value.go:460 +0x5f6\nreflect.Value.Call(0x1e97780, 0x2398b80, 0x13, 0xc0003d3560, 0x1, 0x1, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/reflect/value.go:321 +0xb4\ngo.uber.org/cadence/internal.(*activityExecutor).Execute(0xc00078c300, 0x27eda60, 0xc000d2b8c0, 0x0, 0x0, 0x0, 0x390bc40, 0xc00120e210, 0x24, 0xc000149800, ...)\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_worker.go:936 +0x3b4\ngo.uber.org/cadence/internal.(*activityTaskHandlerImpl).Execute(0xc0007dc280, 0x22ef3e0, 0x21, 0xc000dbed10, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_task_handlers.go:1809 +0x911\ngo.uber.org/cadence/internal.(*activityTaskPoller).ProcessTask(0xc00044f3b0, 0x1dd6a00, 0xc00078c420, 0x27f00e0, 0xc000715e80)\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_task_pollers.go:872 +0x1b8\ngo.uber.org/cadence/internal.(*baseWorker).processTask(0xc00001c2a0, 0x1dd6a00, 0xc00078c420)\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_worker_base.go:300 +0x127\ncreated by go.uber.org/cadence/internal.(*baseWorker).runTaskDispatcher\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_worker_base.go:247 +0x105","stacktrace":"go.uber.org/cadence/internal.(*activityTaskHandlerImpl).Execute.func3\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_task_handlers.go:1784\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:679\nruntime.panicdottypeE\n\t/usr/local/go/src/runtime/iface.go:255\ngithub.com/uber/cadence/service/worker/scanner.TaskListScavengerActivity\n\t/cadence/service/worker/scanner/workflow.go:192\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:460\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:321\ngo.uber.org/cadence/internal.(*activityExecutor).Execute\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_worker.go:936\ngo.uber.org/cadence/internal.(*activityTaskHandlerImpl).Execute\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_task_handlers.go:1809\ngo.uber.org/cadence/internal.(*activityTaskPoller).ProcessTask\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_task_pollers.go:872\ngo.uber.org/cadence/internal.(*baseWorker).processTask\n\t/go/pkg/mod/go.uber.org/cadence@v0.11.3-0.20200408211929-2e8992a5ef2d/internal/internal_worker_base.go:300"}
```

**To Reproduce**
Is the issue reproducible? 
- [Yes]

**Steps to reproduce the behavior:**
Install cadence using docker with postgres for persistence

**Expected behavior**
Do not think we should be seeing above errors

**Comment by longquanzheng** [comment] 2021-01-22 05:23
You probably using 0.15.x

the panic is from https://github.com/uber/cadence/blob/v0.15.0/service/worker/scanner/workflow.go#L192
This bug is fixed in https://github.com/uber/cadence/pull/3584 and release in 0.16.0

Also https://github.com/uber/cadence/pull/3739 disable history scanner by default from 0.17.0

99% of the users won't need it(only need it when you have disk space issue with your database, and you know that it's caused by lots of timeout causing space leakage. ). And you can ignore the error, or disable the history scanner yourself if you don't want to upgrade to 0.17.0 or 0.16.0

**Closed** 2024-03-18 10:57 UTC
