### ISSUE TITLE
StickyExecution: API RespondDecisionTaskFailed

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#371] opened 2017-10-09 21:13 UTC
Use to move sticky task from WorkerTaskList to its original task list.
Need to define a few enum type for failure reason, and with optional details. This could also be used to troubleshooting issues like decider panic.

**Comment by molteanu** [comment] 2017-11-01 16:53
Dupe of #117

**Closed by molteanu** 2017-11-01 16:53 UTC
