### ISSUE TITLE
ChildWorkflows not being retried with MySQL persistence

### ISSUE THREAD

**Issue by lansing** [uber/cadence#3351] opened 2020-06-19 00:44 UTC
**Describe the bug**
We've been unable to get child workflows to retry, regardless of what we provide as the ChildWorkflowOptions' RetryOptions (I've tried numerous permutations), when running Cadence with MySQL as the persistence store. When running the same workflows against a difference Cadence environment using Cassandra, the child workflows are retried as expected.

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**

I have modified one of the Java client samples to reproduce this.

1. Check out my fork of the cadence-java-samples repo: https://github.com/lansing/cadence-java-samples

2. Start a Cadence environment locally using docker-compose-mysql.yaml. I have included a copy in the above repo for convenience:
`docker-compose -f docker-compose-mysql.yml up`

3. Register the sample domain: 
`./gradlew -q execute -PmainClass=com.uber.cadence.samples.common.RegisterDomain`

4. Run my modified HelloChild workflow. I've added RetryOptions/ChildWorkflowOptions to the child workflow, and then I throw a RuntimeException inside the child workflow. 
`./gradlew -q execute -PmainClass=com.uber.cadence.samples.hello.HelloChild`

5. Observe the Cadence UI, and notice that both parent and child workflows are immediately failed with a single attempt for each, rather than having three attempts of the child workflow as specified in the RetryOptions.

6. For good measure, stop the docker-compose Cadence environment, and start one using Cassandra (I also included this yaml file): `docker-compose -f docker-compose.yml up`. Register the sample domain, then run the modified HelloChild again. Observe how GreetingChild::composeGreeting has three separate runs before failing. 

**Expected behavior**
Child workflows should be retried according to the RetryOptions. In the case of the sample code linked to above, the child workflow should be run three times.

**Comment by visaals** [comment] 2020-11-20 16:07
We are doing our final testing after migrating our codebase to Cadence and just ran into this huge bug as well 😞 

A lot of our code relies on child workflow retry policies. Is there any estimate when this will be fixed? 

[Here's the post detailing the child workflow retry issues](https://community.temporal.io/t/retryoptions-setdonotretry-documentation-mismatch/1038/6)

**Comment by longquanzheng** [comment] 2020-11-20 17:44
@lansing thanks so much for reporting the issue. 
@visaals sorry to hear that. I will look into that today and get it fix ASAP. I think it should be quick fix, but I will get back to you when I root cause it.

**Comment by longquanzheng** [comment] 2020-11-20 23:21
We need https://github.com/uber/cadence/issues/3779 to prevent this feature getting broken again

**Comment by longquanzheng** [comment] 2020-11-20 23:31
Hi @lansing and @visaals 
thanks again for reporting it. 

I have root caused the issue and posted a PR out. While you are waiting for merging/release, in case you need I have patched the fix into an image based on latest release 0.15.1.

```
ubercadence/qlong-server:0.15.2 and ubercadence/qlong-server:0.15.2-auto-setup
```
I have tried the code @lansing provided and the fix works for me locally.  Thanks @lansing for providing such detailed instruction, very appreicate it. 

Let me know if it doesn't work.

**Comment by longquanzheng** [comment] 2020-11-20 23:57
>When running the same workflows against a difference Cadence environment using Cassandra, the child workflows are retried as expected

also @lansing , from what I found, I believe the bug is unrelated to Cassandra/MySQL. The bug is introduced in some version upgrade. Can you confirm that?

**Comment by visaals** [comment] 2020-11-23 21:33
> Hi @lansing and @visaals
> thanks again for reporting it.
> 
> I have root caused the issue and posted a PR out. While you are waiting for merging/release, in case you need I have patched the fix into an image based on latest release 0.15.1.
> 
> `ubercadence/qlong-server:0.15.2` and `ubercadence/qlong-server:0.15.2-auto-setup`
> 
> I have tried the code @lansing provided and the fix works for me locally. Thanks @lansing for providing such detailed instruction, very appreicate it.
> 
> Let me know if it doesn't work.

Thank you @longquanzheng! We will let you know if the issue happens again. 

On the topic of retry policies, can you also verify if this [Javadoc]( https://www.javadoc.io/doc/com.uber.cadence/cadence-client/latest/com/uber/cadence/common/RetryOptions.Builder.html#setDoNotRetry-java.lang.Class...-) is still up to date for `setDoNotRetry`? 

It seems like the Javadoc is wrong because of this [RpcRetryer](https://github.com/uber/cadence-java-client/blob/master/src/main/java/com/uber/cadence/internal/common/RpcRetryer.java#L141-L147) code. 

Thanks again for being so quick.

**Comment by longquanzheng** [comment] 2020-11-24 04:12
> > Hi @lansing and @visaals
> > thanks again for reporting it.
> > I have root caused the issue and posted a PR out. While you are waiting for merging/release, in case you need I have patched the fix into an image based on latest release 0.15.1.
> > `ubercadence/qlong-server:0.15.2` and `ubercadence/qlong-server:0.15.2-auto-setup`
> > I have tried the code @lansing provided and the fix works for me locally. Thanks @lansing for providing such detailed instruction, very appreicate it.
> > Let me know if it doesn't work.
> 
> Thank you @longquanzheng! We will let you know if the issue happens again.
> 
> On the topic of retry policies, can you also verify if this [Javadoc](https://www.javadoc.io/doc/com.uber.cadence/cadence-client/latest/com/uber/cadence/common/RetryOptions.Builder.html#setDoNotRetry-java.lang.Class...-) is still up to date for `setDoNotRetry`?
> 
> It seems like the Javadoc is wrong because of this [RpcRetryer](https://github.com/uber/cadence-java-client/blob/master/src/main/java/com/uber/cadence/internal/common/RpcRetryer.java#L141-L147) code.
> 
> Thanks again for being so quick.

yeah, I think "List of exceptions to retry" should be "List of exceptions to not retry". I think it's a typo. 

Is that what you mean?

**Comment by longquanzheng** [comment] 2020-11-25 19:54
@lansing  @visaals 
The fix is merged into master and will be included in the coming release(within a few days).
Also I have made a patch images for you 
```
ubercadence/qlong-server:0.15.2 
and 
ubercadence/qlong-server:0.15.2-auto-setup
```
If you want to run it.

I am closing this issue, but feel free to re-open if you think we still need it.

**Closed by longquanzheng** 2020-11-25 19:54 UTC
Labels: sql

**Comment by lansing** [comment] 2020-11-25 20:47
Thanks @longquanzheng. We probably won't get a chance to test it until after the proper release is made, but I'll get back in touch if we see further issues. Really appreciate the fix, this will definitely help us make our systems more robust.
