### ISSUE TITLE
[Feature] Support TLS + authentication

### ISSUE THREAD

**Issue by hazcod** [uber/cadence#2538] opened 2019-09-13 13:39 UTC
Currently I see no way to add authentication between the cadence server and cadence clients.
Would mutual TLS be an option here?

**Comment by samarabbas** [comment] 2019-09-13 15:53
@hazcod thanks for filing this issue.  We are working on adding TLS support for Cadence.  [Here](https://github.com/uber/cadence/issues/2018) tracking this.

**Comment by samarabbas** [comment] 2019-09-13 15:54
Duplicate of #2018

**Closed by samarabbas** 2019-09-13 15:54 UTC
