### ISSUE TITLE
hint from server when a continue as new is recommanded

### ISSUE THREAD

**Issue by yiminc** [uber/cadence#1331] opened 2018-12-12 18:40 UTC
It would be great if server could put a hint on every decision task started event that a continueAsNew is recommended based on history size/count.

Be sure that the transient decision started event should have the same hint as the actual event when it is write to history otherwise the replay will break on client side.

Currently, client side needs extra logic to control when to do continue as new and change that logic on client side is easy to break determinism.

**Comment by yiminc** [comment] 2018-12-12 18:44
This will be very useful for autobots.

**Comment by dmetzgar** [comment] 2019-05-09 22:00
Duplicate of #174

**Closed by dmetzgar** 2019-05-09 22:00 UTC
