### ISSUE TITLE
[QUESTION] Are retries of unregistered workflow methods the intended behavior?

### ISSUE THREAD

**Issue by crux-ymironoff** [uber/cadence#2958] opened 2020-01-06 15:58 UTC
When using the command line interface [CLI], a misspelled workflow method name causes the workflow start request to become stuck in "retry" state where Cadence services keep requesting workers to execute it, even though there is no matching workflow method registered.

The workflow cancel command reports "success", however, the workflow remains listed in an "open" state and the associated worker process dumps the "Unknown workflow type" + stack error into the log in perpetuity.

Is this intended behavior?

**Comment by mfateev** [comment] 2020-01-06 18:12
Yes, it is by design. Cadence approach is to treat such failures as _intermittent_. It is not obvious when coming from request/reply world, but in the scale of the processes that might run for months a worker not supporting some workflow type is an intermittent error that can be fixed by a code deployment. It also eliminates a potential race condition in deploying code that starts workflows and implements them. There is a configuration option [NonDeterministicWorkflowPolicy](https://github.com/uber/cadence-java-client/blob/cbe3706e2094e0abe4855b9afad1d58c86d7adfe/src/main/java/com/uber/cadence/worker/WorkflowImplementationOptions.java#L36) that changes this behavior to failing workflow on any such error.

Cancellation is by definition gives ability to the workflow to perform all the necessary cleanup which is not possible while worker is not running or doesn't contain the workflow definition code. For termination without any cleanup use "terminate" command which is like "kill -9".

**Comment by crux-ymironoff** [comment] 2020-01-08 00:59
Thanks!

**Closed** 2020-01-28 22:26 UTC
