### ISSUE TITLE
Add an initial cadence domain in the Docker image

### ISSUE THREAD

**Issue by sagikazarmark** [uber/cadence#1622] opened 2019-03-29 21:25 UTC
IMHO Cadence domain is analogue of a database. Most official database images offer an option (usually an environment variable) to create a domain when the container is first started. This is mostly useful in development environments to avoid manual steps in the quick setup guide.

Something similar would be nice in case of Cadence as well.

Currently the only problem I see is there is no state in the container (which is not a problem per se), but there is no way to track whether the domain is created or not, other than in the cassandra database of course. However, there is no "ensure" option in the cadence CLI. So if the domain creation fails, where is no way to tell if it is because the domain already exists or for some other reason.

A possible solution would be adding an "ensure" command in the cadence CLI that creates the domain in an idempotent way (if necessary).

**Comment by meiliang86** [comment] 2020-03-01 16:32
Duplicate of https://github.com/uber/cadence/issues/2343

**Closed by meiliang86** 2020-03-01 16:32 UTC
