### ISSUE TITLE
Do not complete on return activities

### ISSUE THREAD

**Issue by JuanPalacios** [uber/cadence#3251] opened 2020-05-11 07:41 UTC
Hello,
We are trying to use the doNotCompleteOnReturn activities for asynch external operations but we can't use a business id to correlate the request reply lifecycle. Could you explain how to do it if it is posible. We are using de java cadence client.

Thanks in advance

**Comment by mfateev** [comment] 2020-05-11 17:44
Unfortunately currently setting business ID on an activity is not yet supported by the Java client.

**Comment by JuanPalacios** [comment] 2020-05-11 20:06
Thanks Maxim, Is it the java client ready to production? Because there is no way to support a simple request reply lifecycle (asynch), synchronous updates are not support and this feature neither.  There is no way to comunicate with the workflow from the external world consistently?

**Comment by meiliang86** [comment] 2020-05-11 22:52
@JuanPalacios Java client is Production ready. I think the way you use AsyncActivityCompletion is that inside the activity you will need to send the task token out to whoever needs to complete the activity.
Aside from async activity completion, have you looked at signals and (consistent) workflow query? You will only need workflowID (i.e. your business id) to do signal and query.

**Comment by JuanPalacios** [comment] 2020-05-12 06:21
Thanks
We know well Cadence but we start to lose some signal because of this isuee #537. I'm trying to find a solution.

**Comment by meiliang86** [comment] 2020-05-12 15:31
It's not a normal scenario to lose signals. Most of the causes mentioned in #537 are bugs that can/should be fixed during deployment (serialization, etc). Regardless, from Cadence perspective, signals are recorded in History and are never "lost". One way to recover them is to use reset, if you design your workflow to allow the progress to go back.

**Closed** 2024-11-01 22:47 UTC
Labels: improvement
